### ISSUE TITLE
Component error: protexiom - Integration 'protexiom' not found

### ISSUE THREAD

**Issue by sbik38** [Pschittt/HASS-Somfy-Protexiom#4]
Hello

J'essaye d'installer ton Custom_Components à mon HA. 
J'ai créé un dossier protexiom sous mon Custom_components et j'ai copié tous tes fichiers dedans
J'ai ajouté les lignes dans le Configuration.yaml
j'ai aussi saisi tous les Password, URL, Codes dans Secrets.yaml
Quand je lance le 'Check configuration" avant de redemarrer mon HA, j'obtiens l'erreur ci-dessous (et donc impossible de redemarrer HA).
Une idée de ce que j'ai raté ? Merci

![image](https://user-images.githubusercontent.com/60422995/89341727-07ac4d80-d6a2-11ea-9c5c-5ea0a1d7a705.png)

**Comment by Pschittt** [comment]
Bonjour,

Là comme ça, aucune idée.
Il faudrait jeter un coup d'oeil au fichier de conf, et au nom du répertoire dans custom_component.

Ils doivent avoir le même nom.

**Comment by carfnann** [comment]
> Hello
> 
> J'essaye d'installer ton Custom_Components à mon HA. J'ai créé un dossier protexiom sous mon Custom_components et j'ai copié tous tes fichiers dedans J'ai ajouté les lignes dans le Configuration.yaml j'ai aussi saisi tous les Password, URL, Codes dans Secrets.yaml Quand je lance le 'Check configuration" avant de redemarrer mon HA, j'obtiens l'erreur ci-dessous (et donc impossible de redemarrer HA). Une idée de ce que j'ai raté ? Merci
> 
> ![image](https://user-images.githubusercontent.com/60422995/89341727-07ac4d80-d6a2-11ea-9c5c-5ea0a1d7a705.png)

Hello sbik38

j'ai exactement le même soucis.
j'ai double check le nom du répertoire mais rien n'y fait, j'ai même tenter de renommer le nom du repertoire et aussi dans la config.

Est ce que tu as réussi?

merci

**Comment by GitHubMe78** [comment]
Bonjour,
Idem.
Dans les logs j'ai le message d'erreur:

2021-11-10 10:29:14 ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'protexiom' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
On dirait qu'il y a eu des modifs à effectuer depuis début avril 2021 avec le fichier manifest.json et Hassfest.
Une idée ?

**Comment by Pschittt** [comment]
Je viens de mettre à jour le fichier manifest pour y intégrer un numéro de version. HA le demande depuis quelques versions.
Cela devrait fonctionner à présent.

**Comment by GitHubMe78** [comment]
Merci.
Mais maintenant j'ai:
Traceback (most recent call last):
  File "/config/custom_components/protexiom/__init__.py", line 51, in setup
    elements = somfy.get_elements()
  File "/config/custom_components/protexiom/somfy.py", line 137, in get_elements
    state_soup = self._beautiful_it_and_check_error(state_html)
  File "/config/custom_components/protexiom/somfy.py", line 173, in _beautiful_it_and_check_error
    self._check_error(soup)
  File "/config/custom_components/protexiom/somfy.py", line 188, in _check_error
    raise SomfyException("Droit d'acces insuffisant")
custom_components.protexiom.somfy.SomfyException: "Droit d'acces insuffisant"

**Comment by GitHubMe78** [comment]
On est bien d'accord que:
 url: "http://adresse.com:port"
et 
codes:
key_A1: 9999 # sans !
...
key_F5: 0000
