### ISSUE TITLE
Initialisation de l'intégration Protexiom impossible

### ISSUE THREAD

**Issue by jeyce** [Pschittt/HASS-Somfy-Protexiom#5]
Bonjour, 

J'ai des soucis lors du démarrage de Protexium.
Les URL et mots de passe ont bien été renseignés et fonctionnent

Outre l'histoire d'ajouter la version dans le manifest,  auriez-vous une piste pour que l'initialisation soit débloqué ?

Merci d'avance

Env : Raspberry 3, install via image HA

```
 2021-03-14 00:05:36 WARNING (MainThread) [homeassistant.loader] You are using a custom integration protexiom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-14 00:05:36 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'protexiom'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'protexiom'
2021-03-14 00:05:44 ERROR (SyncWorker_1) [custom_components.protexiom] Error when trying to log in
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/mechanize/_mechanize.py", line 266, in _mech_open
url.get_full_url
AttributeError: 'str' object has no attribute 'get_full_url'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/protexiom/__init__.py", line 50, in setup
somfy.login()
File "/config/custom_components/protexiom/somfy.py", line 38, in login
login_response = self.browser.open(self.url + "/m_login.htm")
File "/usr/local/lib/python3.8/site-packages/mechanize/_mechanize.py", line 257, in open
return self._mech_open(url_or_request, data, timeout=timeout)
File "/usr/local/lib/python3.8/site-packages/mechanize/_mechanize.py", line 273, in _mech_open
raise BrowserStateError("can't fetch relative reference: "
mechanize._mechanize.BrowserStateError: can't fetch relative reference: not viewing any document
2021-03-14 00:05:49 ERROR (MainThread) [homeassistant.setup] Setup failed for protexiom: Integration failed to initialize.
```

**Comment by jeyce** [comment]
mes plates excuses : j'avais oublié le 'http:://' dans l'URL
Le fichier de test local m'a bien aidé

Merci !
